### ISSUE TITLE
ソースコード記号を使うと保存できず固まる

### ISSUE THREAD

**Issue by kitmasaya** [kujirahand/konawiki2#11]
KonaWiki 2.2.3を利用しています。

ソースコード記号を用いてプログラムのソースコードを保存しようとしたところ保存できない場面に出くわしました。

対象のソースコードを切り詰めていくと、以下のコードだけでも固まってしまい保存できません。

```
{{{
fopen(argv[1], "rt");
}}}
```

KonaWikiの再設置等も試してみましたが同様でした。

Issueの投稿が初めてのため、不足情報やログの必要があればご連絡いただけましたら追記いたします。

設置サーバはlolipopのエコノミーになります。

**Comment by kujirahand** [comment]
私もロリポップを使っているのですが、
konawikiで書き込んだテキストが、WAFによりブロックされる現象が発生します。
WAFの設定をオフにして試してみてください。

WAFがオンになっている限り、konawikiだけに関わらず、別のCMSでも同様のエラーになると思います。
ご確認ください！

**Comment by kujirahand** [comment]
一定期間経ちましたので、閉じますね。
